services:
  ota-analyzer:
    image: ghcr.io/virgooooox/ota-analyzor:latest
    container_name: ota-analyzer
    ports:
      - "8000:8000"
    environment:
      DATA_DIR: /app/data
      UPLOAD_DIR: /app/uploads
      TAGS_FILE: /app/tags.json
    volumes:
      - ./Raw Data:/app/data
      - ./uploads:/app/uploads
      - ./tags.json:/app/tags.json
    restart: unless-stopped
